### PR TITLE
added button to remove userid form localstorage

### PR DESCRIPTION
**Pull request by NGR-NP**
when the button is pressed for 2 second  then it will remove userid from local Storage and show fire svg on bottom along with toast message on upper left corner as "user id is deleted !!" for 5 second

### CODE REVIEW

**Comment by maheshbasnet089** [comment]
Local storage ma userId vako Bela matra show garnu paryo yo button and check the mobile responsive view tesko once

**Comment by NGR-NP** [comment]
Yes, I agree with you that the previous code was a mess and awful. Now, I have updated it and approached it differently. I have added a flame sound when the user ID is successfully deleted. Additionally, if there is no user ID available, I have implemented a shake animation for the button. Moreover, if the user is on a phone, the phone will vibrate for 400 milliseconds.

**Comment by maheshbasnet089** [comment]
We need to hide it when there is no userid @NGR-NP sir

**Comment by maheshbasnet089** [comment]
ok i m merging it sir

**Pull request merged**
