### PR TITLE
Refactored the whole code base

### PR DESCRIPTION
**Pull request by arpan404**
Made the code base more maintainable by organizing different components in different folders and made some change in styles

### CODE REVIEW

**Comment by arpan404** [comment]
Made changed to the design of modal of Search Code

**Comment by arpan404** [comment]
image
Redesigned the add code page entirely and made it optimized

**Comment by arpan404** [comment]
Next, will redesign view code section

**Comment by maheshbasnet089** [comment]
confilcting files tapShareFrontend/src/components/receiverEmailInputField.jsx
resolved it first @arpan404 , i won't be able to merge it without resolving

**Comment by maheshbasnet089** [comment]
The search bar is not being autofocused when opened , user had to click on the search bar manually to select the search bar.

**Comment by maheshbasnet089** [comment]
Still conflict on same file , receiverEmailInputfield.jsx

**Comment by arpan404** [comment]
@maheshbasnet089 , merge it now

**Comment by maheshbasnet089** [comment]
Conflict was resolved will review and merge it

**Pull request merged**
