### PR TITLE
Fixed Errors & added new features

### PR DESCRIPTION
**Pull request by arpan404**

### CODE REVIEW

**Comment by maheshbasnet089** [comment]
i saw you are using characters for userId in the generateUserId file inside of utility. The userId made of characters lacks our purpose to make it simple to say/remember userId. so would you @arpan404  keep it as it was before i.e number's userId

**Comment by arpan404** [comment]
Just added only two alphabets to make it simpler while maintaining unique userUid for every user

**Comment by maheshbasnet089** [comment]
can we do it 6 digits numbers only no alphabet.

**Comment by arpan404** [comment]
@maheshbasnet089 , there will be high probability of users getting same id when the product grows.

**Pull request merged**
