### PR TITLE
Update readme.md

### PR DESCRIPTION
**Pull request by jay-sambhu**
i have updated some name of the people who are contributing our site

### CODE REVIEW

**Review by NGR-NP — APPROVED** [review]

**Comment by maheshbasnet089** [comment]
do add other contributors name too, see in the contributors in the right side of repo.Umesh Mehta, manik are also their

**Comment by maheshbasnet089** [comment]
Name matra haina contributors haru ko github link ni add gardeu,name ma click garda tya link ma janu parney hunchha

**Review by arpan404 — CHANGES_REQUESTED** [review]
Instead of adding name directly to readme.md, make Contributors.md file, then write the contributors name and link to their github account.

**Comment by maheshbasnet089** [comment]
> Instead of adding name directly to readme.md, make Contributors.md file, then write the contributors name and link to their github account.

@0Aashish are you on it ?

**Pull request closed without merging**
